spring.application.name=demoLdap

spring.ldap.urls=${SPRING_LDAP_URLS:ldap://localhost:10389}
spring.ldap.base=${SPRING_LDAP_BASE:dc=example,dc=com}
spring.ldap.username=${SPRING_LDAP_USERNAME:uid=admin,ou=system}
spring.ldap.password=${SPRING_LDAP_PASSWORD:secret}

spring.ldap.pooled=false

server.port=8081