spring.application.name=usersByOrgApi
server.port=8082

spring.ldap.urls=ldap://localhost:10389
spring.ldap.base=dc=example,dc=com
spring.ldap.username=uid=admin,ou=system
spring.ldap.password=secret
spring.ldap.pooled=false
cors.allowed-origin=*